### ISSUE TITLE
DatePicker `locale` prop is hardcoded to "sk"

### ISSUE THREAD

**Issue by senecolas** [BRACKETS-by-TRIAD/craftable-pro-docs#20]
## Issue
`DatePicker.vue` is in slovak by default and can't be change

## Proposal
V-calendar `locale` prop can be a prop of `DatePicker.vue` and in english by default, or in the local language of the user

**Comment by timoransky** [comment]
Hi @senecolas!
Thank you for the issue report. I will try to release a bug fix for this ASAP, but it might take a few days.
I will keep you updated 🤗

**Comment by timoransky** [comment]
Hi @senecolas 
This was also fixed in the latest version ([1.1.7](https://docs.craftable.pro/changelog#v117---2023-04-13)), just as you proposed. 

We’re grateful for the bug reports and feature requests. They’ve been incredibly helpful in identifying issues that we missed. 😅 I hope you will keep using Craftable PRO and don’t hesitate to let us know if you encounter anything else that needs our attention. 
Thank you again! 🤗
